# Generated by Django 3.2.11 on 2022-01-18 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_auto_20220118_1952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
