version: "3.3"
   
services:
  web:
    container_name: web_proteomics_qc_production
    restart: always
    user: ${UID}
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=production
    command: python server.py
    volumes:
      - ./app/:/app/
      - ./lib/lrg_omics/:/lrg-omics/
      - ${DATALAKE}:/datalake/
      - ${MEDIA}:/appmedia/
      - ${STATIC}:/static/
      - ${COMPUTE}:/compute/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    links:
      - redis:redis
  
  db:
    container_name: db_proteomics_qc_production
    restart: always
    image: postgres:13.4
    volumes:
      - ${DB}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    container_name: redis_proteomics_qc_production
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    container_name: celery_proteomics_qc_production
    restart: always
    user: ${UID}
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: bash -c "celery -A main worker -l info --concurrency ${CONCURRENCY}"
    env_file:
      - ./.env    
    volumes:
      - ./app/:/app/
      - ./lib/lrg_omics/:/lrg-omics/
      - ${DATALAKE}:/datalake/      
      - ${COMPUTE}:/compute/
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
      - redis
      - web

