site_name: Proteomics QC
nav:
    - Home: index.md
    - Installation: installation.md
    #- User Manual: manual.md
    - Access the admin panel: how-to-access-the-admin-panel.md
    - Create a project: how-to-add-a-project.md
    - Create a pipeline: how-to-add-a-pipeline.md
    - Submit RAW files: how-to-submit-raw-files.md
    - Datalake: datalake.md
    - RawTools: rawtools-issues.md
    - MaxQuant: maxquant-issues.md
    - API: api.md
    - About: about.md
    
theme: readthedocs
