# Generated by Django 3.2.15 on 2023-03-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_dashapp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashApp",
        ),
    ]
