# Generated by Django 3.2.5 on 2021-08-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maxquant", "0006_maxquantpipeline_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maxquantpipeline",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
