# Generated by Django 3.2.12 on 2022-04-07 17:15

from django.db import migrations, models
import main.settings
import maxquant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('maxquant', '0014_auto_20220204_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='maxquant_pipepline_id',
            new_name='maxquant_pipeplineid',
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='orig_file',
            field=models.FileField(max_length=1000, storage=main.settings.MediaFileSystemStorage(location='/datalake'), upload_to='upload', validators=[maxquant.validators.validate_file_is_rawfile]),
        ),
    ]
