# Generated by Django 3.2.3 on 2021-07-08 00:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
